# dbt_project.yml
name: 'iceberg_analytics'
version: '1.0.0'
config-version: 2

profile: 'iceberg'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

require-dbt-version: [">=1.5.0", "<2.0.0"]

models:
  iceberg_analytics:
    materialized: table

    bronze:
      materialized: table
      description: "Raw data layer from Kafka"

    silver:
      materialized: table
      description: "Cleaned and enriched data"

    gold:
      materialized: table
      description: "Business-ready aggregations"

on-run-start:
  - "{{ log('Starting dbt run...', info=true) }}"

on-run-end:
  - "{{ log('Completed dbt run!', info=true) }}"
