ecommerce_lakehouse:
  target: 'dev'
  outputs:
    dev:
      type: 'spark'
      method: 'thrift'
      host: 'localhost'
      port: 10000
      user: 'dbt'
      schema: 'default'
      threads: 4
      connect_retries: 5
      connect_timeout: 10
      session_args:
        spark.hadoop.io.native.lib.available: "false"
